# Generated by Django 4.0.2 on 2022-02-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID дела в BX24')),
                ('COMPANY_ID', models.PositiveIntegerField(verbose_name='ID компании в BX24')),
                ('COMPLETED', models.CharField(choices=[('Y', 'Завернено'), ('N', 'Не завершено')], max_length=1, verbose_name='Заершено дело или нет')),
                ('DIRECTION', models.CharField(choices=[('0', '-'), ('1', 'Входящее'), ('2', 'Исходящее')], max_length=1, verbose_name='Направление дела (входящее/исходящее)')),
                ('TYPE_ID', models.CharField(choices=[('1', 'Встреча'), ('2', 'Звонок'), ('3', 'Задача'), ('4', 'Письмо')], max_length=1, verbose_name='Тип дела (входящее/исходящее)')),
                ('STATUS', models.CharField(choices=[('0', '-'), ('1', '-'), ('2', 'Ожидается'), ('3', 'Завершено'), ('4', 'Завершено автоматически')], max_length=1, verbose_name='Статус дела (входящее/исходящее)')),
                ('CREATED', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания дела')),
                ('END_TIME', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения дела')),
                ('FILES', models.URLField(blank=True, max_length=250, null=True, verbose_name='URL привязанного файла')),
                ('active', models.BooleanField(default=True, verbose_name='Дело не удалено из Битрикс24')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
            },
        ),
        migrations.CreateModel(
            name='CountWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_count_working', models.DateField(verbose_name='Дата записи')),
                ('count_working_days', models.IntegerField(verbose_name='Количество звонков')),
            ],
            options={
                'verbose_name': 'Количество рабочих дней в месяце',
                'verbose_name_plural': 'Количество рабочих дней в месяце',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя в BX24')),
                ('LAST_NAME', models.CharField(blank=True, max_length=35, null=True, verbose_name='Фамилия')),
                ('NAME', models.CharField(blank=True, max_length=35, null=True, verbose_name='Имя')),
                ('WORK_POSITION', models.CharField(blank=True, max_length=75, null=True, verbose_name='Должность')),
                ('UF_DEPARTMENT', models.PositiveIntegerField(verbose_name='ID департамета')),
                ('ACTIVE', models.BooleanField(default=True, verbose_name='Пользователь активен (не уволен)')),
                ('URL', models.URLField(max_length=150, verbose_name='URL пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CALL_ID', models.CharField(db_index=True, max_length=75, unique=True, verbose_name='ID дела в BX24')),
                ('CALL_TYPE', models.CharField(choices=[('1', 'Исходящий'), ('2', 'Входящий'), ('3', 'Входящий с перенаправлением'), ('4', 'Обратный звонок')], max_length=1, verbose_name='Тип звонка')),
                ('PHONE_NUMBER', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН компании')),
                ('CALL_DURATION', models.PositiveIntegerField(verbose_name='Длительность звонка')),
                ('CALL_START_DATE', models.DateTimeField(verbose_name='Дата звонка')),
                ('CRM_ACTIVITY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='activityapp.activity', verbose_name='Дело')),
                ('PORTAL_USER_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='activityapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='CallingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plan_calls', models.DateField(verbose_name='Дата плана звонка')),
                ('count_calls', models.IntegerField(verbose_name='Количество звонков')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_plan', to='activityapp.user', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Планируемое кол-во звонков в месяц',
                'verbose_name_plural': 'План по звонкам в месяц',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='RESPONSIBLE_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='activityapp.user', verbose_name='Пользователь'),
        ),
    ]
