# Generated by Django 4.0.2 on 2022-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0002_user_status_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingplan',
            name='count_calls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество звонков'),
        ),
    ]
