# Generated by Django 4.0.2 on 2022-03-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0004_user_allowed_edit_user_allowed_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calendar', models.DateField(unique=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('week', 'Не рабочий день'), ('work', 'Рабочий день')], default='work', max_length=4, verbose_name='Статус дня (рабочий/нерабочий)')),
            ],
            options={
                'verbose_name': 'Запись дня из производственного календаря',
                'verbose_name_plural': 'Список дней производственного календаря',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='ALLOWED_EDIT',
            field=models.CharField(choices=[('0', 'Запрещено'), ('1', 'Ограниченно разрешено'), ('2', 'Разрешено')], default='0', max_length=1, verbose_name='Доступ к редактированию данных'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ALLOWED_SETTING',
            field=models.BooleanField(default=False, verbose_name='Доступ к настройкам приложения'),
        ),
        migrations.CreateModel(
            name='CallsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_calls', models.IntegerField(blank=True, null=True, verbose_name='Количество звонков')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_plan', to='activityapp.productioncalendar', verbose_name='Дата из производственного календаря')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_plan', to='activityapp.user', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'План по звонкам на день',
                'verbose_name_plural': 'Планы по звонкам на день',
                'unique_together': {('calendar', 'employee')},
            },
        ),
    ]
