# Generated by Django 4.0.2 on 2022-03-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0005_productioncalendar_alter_user_allowed_edit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callingplan',
            options={'verbose_name': 'Планируемое кол-во звонков в месяц (OLD)', 'verbose_name_plural': 'План по звонкам в месяц (OLD)'},
        ),
        migrations.AlterModelOptions(
            name='callsplan',
            options={'verbose_name': 'План по звонкам на день (NEW)', 'verbose_name_plural': 'План по звонкам (NEW)'},
        ),
        migrations.AlterModelOptions(
            name='countworkingdays',
            options={'verbose_name': 'Количество рабочих дней в месяце (OLD)', 'verbose_name_plural': 'Количество рабочих дней в месяце (OLD)'},
        ),
        migrations.AlterModelOptions(
            name='productioncalendar',
            options={'verbose_name': 'День из роизводственного календаря (NEW)', 'verbose_name_plural': 'Производственный календарь (NEW)'},
        ),
    ]
