# Generated by Django 4.0.2 on 2022-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(verbose_name='Дата комментария'),
        ),
    ]
