# Generated by Django 4.0.2 on 2022-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0008_alter_comment_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_comment_add',
            field=models.DateTimeField(default='2022-03-01', verbose_name='Дата добавления комментария'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateField(verbose_name='Дата комментария'),
        ),
    ]
