# Generated by Django 4.0.2 on 2022-03-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0010_activity_owner_id_activity_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='OWNER_NAME',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название сущности к которой привязан звонок'),
        ),
    ]
