# Generated by Django 4.0.2 on 2022-04-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0011_alter_activity_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsplan',
            name='plan_completed',
            field=models.BooleanField(default=False, verbose_name='План на день выполнен'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_verified',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='comment',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Комментарий подтвержден'),
        ),
        migrations.AddField(
            model_name='comment',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by_user', to='activityapp.user', verbose_name='Пользователь который подтвердил комментарий'),
        ),
    ]
